"""Add product table

Revision ID: 1861e8d220c4
Revises: 1cbff05e85ae
Create Date: 2025-02-11 20:19:10.014356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1861e8d220c4'
down_revision = '1cbff05e85ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product__details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Product_name', sa.String(length=255), nullable=False),
    sa.Column('Price', sa.String(length=255), nullable=False),
    sa.Column('Qty', sa.String(length=255), nullable=False),
    sa.Column('Discount', sa.String(length=15), nullable=False),
    sa.Column('Disc_price', sa.String(length=255), nullable=False),
    sa.Column('Product_image', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Product_name')
    )
    with op.batch_alter_table('product_add', schema=None) as batch_op:
        batch_op.drop_index('Discount')
        batch_op.drop_index('Product_name')
        batch_op.drop_index('Qty')

    op.drop_table('product_add')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_add',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Product_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Price', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Qty', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Discount', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('Disc_price', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('product_add', schema=None) as batch_op:
        batch_op.create_index('Qty', ['Qty'], unique=True)
        batch_op.create_index('Product_name', ['Product_name'], unique=True)
        batch_op.create_index('Discount', ['Discount'], unique=True)

    op.drop_table('product__details')
    # ### end Alembic commands ###
