"""Add product table

Revision ID: 1cbff05e85ae
Revises: de3691f03094
Create Date: 2025-02-11 20:15:58.818965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cbff05e85ae'
down_revision = 'de3691f03094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_add',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Product_name', sa.String(length=255), nullable=False),
    sa.Column('Price', sa.String(length=255), nullable=False),
    sa.Column('Qty', sa.String(length=255), nullable=False),
    sa.Column('Discount', sa.String(length=15), nullable=False),
    sa.Column('Disc_price', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Discount'),
    sa.UniqueConstraint('Product_name'),
    sa.UniqueConstraint('Qty')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_add')
    # ### end Alembic commands ###
