"""Added created_Date column to product_details

Revision ID: 71636689aa05
Revises: eb6779978437
Create Date: 2025-02-12 10:13:08.905930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71636689aa05'
down_revision = 'eb6779978437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product__details', schema=None) as batch_op:
        batch_op.alter_column('Product_image',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product__details', schema=None) as batch_op:
        batch_op.alter_column('Product_image',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
