"""Add product update

Revision ID: 737c6d600f6a
Revises: 1861e8d220c4
Create Date: 2025-02-12 09:17:48.792061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737c6d600f6a'
down_revision = '1861e8d220c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product__details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('PName', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product__details', schema=None) as batch_op:
        batch_op.drop_column('PName')
        batch_op.drop_column('Date')

    # ### end Alembic commands ###
