"""Added created_Date column to product_details

Revision ID: eb6779978437
Revises: 737c6d600f6a
Create Date: 2025-02-12 10:09:36.045321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6779978437'
down_revision = '737c6d600f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product__details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_Date', sa.Date(), nullable=True))
        batch_op.drop_column('Date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product__details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Date', sa.DATE(), nullable=True))
        batch_op.drop_column('created_Date')

    # ### end Alembic commands ###
